import React, { useState, useEffect } from 'react';
import { Card, Table, Button, Form, Modal, Alert, Space, Tag, Typography, Tooltip, message, Input } from 'antd';
import { PlusOutlined, ReloadOutlined, CopyOutlined, ExclamationCircleOutlined, EyeOutlined, EyeInvisibleOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import CustomSelect from '../components/CustomSelect';

const { Text, Paragraph } = Typography;
const { Option } = CustomSelect;

// Interface for mock API calls
interface Team {
  id: string;
  name: string;
  balance?: number; // Team balance field
}

interface ApiKey {
  id: string;
  name: string;
  key: string;
  ownerType: 'personal' | 'team';
  ownerId: string;
  ownerName: string;
  createdAt: string;
  isDisabled?: boolean; // Flag indicating if API key is disabled (insufficient balance)
}

// Mock API calls
const mockFetchTeams = async (): Promise<Team[]> => {
  // In a real environment, this would be fetched from the backend
  return [
    { id: '1', name: 'AI Research Team', balance: 100 },
    { id: '2', name: 'ML Development', balance: 0 }, // Balance is 0, indicating insufficient funds
    { id: '3', name: 'Data Science Group', balance: 50 },
  ];
};

const mockFetchApiKeys = async (): Promise<ApiKey[]> => {
  // In a real environment, this would be fetched from the backend
  return [
    {
      id: '1',
      name: 'Personal API Key',
      key: 'sk-personalkey123456789abcdefghijklmnopqrstuvwxyz',
      ownerType: 'personal',
      ownerId: 'user1',
      ownerName: 'Your Personal Key',
      createdAt: '2023-06-10'
    },
    {
      id: '2',
      name: 'Team API Key',
      key: 'sk-teamkey123456789abcdefghijklmnopqrstuvwxyz',
      ownerType: 'team',
      ownerId: '1',
      ownerName: 'AI Research Team',
      createdAt: '2023-06-15'
    },
    {
      id: '3',
      name: 'ML Dev API Key',
      key: 'sk-mldevkey123456789abcdefghijklmnopqrstuvwxyz',
      ownerType: 'team',
      ownerId: '2', // Corresponds to team with zero balance
      ownerName: 'ML Development',
      createdAt: '2023-07-20'
    }
  ];
};

const ApiKeys: React.FC = () => {
  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [teams, setTeams] = useState<Team[]>([]);
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [newKeyVisible, setNewKeyVisible] = useState(false);
  const [newKeyValue, setNewKeyValue] = useState('');
  const [form] = Form.useForm();
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [regenerateLoading, setRegenerateLoading] = useState<string | null>(null);
  const [visibleKeys, setVisibleKeys] = useState<Set<string>>(new Set());
  const [teamBalances, setTeamBalances] = useState<Record<string, number>>({});

  // Existing key owners (used to check if already exists)
  const [existingOwners, setExistingOwners] = useState<{
    personal: boolean;
    teamIds: string[];
  }>({
    personal: false,
    teamIds: [],
  });

  useEffect(() => {
    fetchApiKeys();
    fetchTeams();
  }, []);
  
  // Check if team balance is sufficient
  const checkTeamBalance = (teamId: string): boolean => {
    return teamBalances[teamId] > 0;
  };

  const fetchApiKeys = async () => {
    try {
      const keys = await mockFetchApiKeys();
      setApiKeys(keys);
      
      // Update existing key owners
      const personal = keys.some(key => key.ownerType === 'personal');
      const teamIds = keys
        .filter(key => key.ownerType === 'team')
        .map(key => key.ownerId);
      
      setExistingOwners({
        personal,
        teamIds,
      });
    } catch (error) {
      console.error('Failed to fetch API keys:', error);
      message.error('Failed to load API keys');
    }
  };

  const fetchTeams = async () => {
    try {
      const teamList = await mockFetchTeams();
      setTeams(teamList);
      
      // Update team balance status
      const balances: Record<string, number> = {};
      teamList.forEach(team => {
        balances[team.id] = team.balance || 0;
      });
      setTeamBalances(balances);
    } catch (error) {
      console.error('Failed to fetch teams:', error);
      message.error('Failed to load teams');
    }
  };

  const showCreateModal = () => {
    form.resetFields();
    setIsModalVisible(true);
  };

  const handleCancel = () => {
    setIsModalVisible(false);
  };

  const handleCreate = async () => {
    try {
      const values = await form.validateFields();
      setConfirmLoading(true);
      
      // Mock API calls
      setTimeout(() => {
        // Generate random API key (in a real environment, this would be generated by the backend)
        const newKey = `sk-${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`;
        
        let ownerName = 'Your Personal Key';
        if (values.ownerType === 'team') {
          const team = teams.find(t => t.id === values.ownerId);
          ownerName = team?.name || '';
        }
        
        const newApiKey: ApiKey = {
          id: Date.now().toString(),
          name: values.name,
          key: newKey, // Store the complete key directly
          ownerType: values.ownerType,
          ownerId: values.ownerType === 'personal' ? 'user1' : values.ownerId,
          ownerName,
          createdAt: new Date().toISOString().split('T')[0]
        };
        
        setApiKeys([...apiKeys, newApiKey]);
        
        // Update existing owners
        if (values.ownerType === 'personal') {
          setExistingOwners({ ...existingOwners, personal: true });
        } else {
          setExistingOwners({
            ...existingOwners,
            teamIds: [...existingOwners.teamIds, values.ownerId]
          });
        }
        
        setConfirmLoading(false);
        setIsModalVisible(false);
        setNewKeyVisible(true);
        setNewKeyValue(newKey);
      }, 1000);
    } catch (error) {
      console.error('Validation failed:', error);
    }
  };

  const handleCopyKey = (key: string) => {
    navigator.clipboard.writeText(key)
      .then(() => {
        message.success('API key copied to clipboard');
      })
      .catch(() => {
        message.error('Failed to copy API key');
      });
  };

  const handleRegenerateKey = (record: ApiKey) => {
    Modal.confirm({
      title: 'Regenerate API Key',
      icon: <ExclamationCircleOutlined style={{ color: '#faad14' }} />,
      content: 'Are you sure you want to regenerate this API key? The current key will be invalidated immediately.',
      onOk() {
        setRegenerateLoading(record.id);
        
        // Mock API calls
        setTimeout(() => {
          // Generate random API key (in a real environment, this would be generated by the backend)
          const newKey = `sk-${Math.random().toString(36).substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`;
          
          // Update the key in the record
          const updatedKeys = apiKeys.map(key => {
            if (key.id === record.id) {
              return { ...key, key: newKey };
            }
            return key;
          });
          
          setApiKeys(updatedKeys);
          setRegenerateLoading(null);
          setNewKeyVisible(true);
          setNewKeyValue(newKey);
        }, 1000);
      },
    });
  };

  const toggleKeyVisibility = (id: string) => {
    setVisibleKeys(prev => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  const formatApiKey = (key: string, isVisible: boolean) => {
    if (isVisible) {
      return key;
    }
    // Show first 6 characters and last 4 characters, replace middle with ••••
    return `${key.substring(0, 6)}${'•'.repeat(20)}${key.substring(key.length - 4)}`;
  };

  const columns: ColumnsType<ApiKey> = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      render: (text, record) => (
        <div>
          {text}
          {record.ownerType === 'team' && !checkTeamBalance(record.ownerId) && (
            <Tag color="red" style={{ marginLeft: 8 }}>
              Disabled
            </Tag>
          )}
        </div>
      ),
    },
    {
      title: 'Account Type',
      dataIndex: 'ownerName',
      key: 'ownerName',
      render: (text, record) => (
        <>
          {record.ownerType === 'personal' ? (
            <Tag color="blue">Personal</Tag>
          ) : (
            <Tag color="green">Team</Tag>
          )}
          {text}
          {record.ownerType === 'team' && !checkTeamBalance(record.ownerId) && (
            <Tooltip title="Team account has insufficient balance, API key has been disabled">
              <ExclamationCircleOutlined style={{ color: '#ff4d4f', marginLeft: 8 }} />
            </Tooltip>
          )}
        </>
      ),
    },
    {
      title: 'API Key',
      dataIndex: 'key',
      key: 'key',
      render: (text, record) => (
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <Text code style={{ 
            fontFamily: 'monospace', 
            flex: 1,
            color: record.ownerType === 'team' && !checkTeamBalance(record.ownerId) ? '#999999' : undefined,
            textDecoration: record.ownerType === 'team' && !checkTeamBalance(record.ownerId) ? 'line-through' : undefined
          }}>
            {formatApiKey(text, visibleKeys.has(record.id))}
          </Text>
          <Button 
            type="text" 
            icon={visibleKeys.has(record.id) ? <EyeInvisibleOutlined /> : <EyeOutlined />} 
            onClick={() => toggleKeyVisibility(record.id)}
            style={{ marginLeft: 8 }}
            disabled={record.ownerType === 'team' && !checkTeamBalance(record.ownerId)}
          />
          <Button 
            type="text" 
            icon={<CopyOutlined />} 
            onClick={() => handleCopyKey(text)}
            style={{ marginLeft: 4 }}
            disabled={record.ownerType === 'team' && !checkTeamBalance(record.ownerId)}
          />
        </div>
      ),
    },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (_, record) => (
        <Space>
          {record.ownerType === 'team' && !checkTeamBalance(record.ownerId) ? (
            <Tooltip title="Please contact team administrator to recharge before using" overlayStyle={{ fontSize: '14px' }}>
              <Button 
                type="text" 
                danger
                onClick={() => message.warning('Please contact team administrator to recharge before using')}
              >
                Contact for Recharge
              </Button>
            </Tooltip>
          ) : (
            <Tooltip title="Regenerate API Key" overlayStyle={{ fontSize: '14px' }}>
              <Button 
                type="text" 
                icon={<ReloadOutlined />} 
                onClick={() => handleRegenerateKey(record)}
                loading={regenerateLoading === record.id}
                className="regenerate-btn"
              >
                Regenerate
              </Button>
            </Tooltip>
          )}
        </Space>
      ),
    },
  ];

  return (
    <Card
      title="API Keys"
      extra={
        <Button 
          type="primary" 
          icon={<PlusOutlined />} 
          onClick={showCreateModal}
        >
          Generate New API Key
        </Button>
      }
      style={{ background: '#141414', border: '1px solid #303030' }}
    >
      <Alert
        message="API Keys allow you to authenticate with our API"
        description="Keep your API keys secure - do not share them in publicly accessible areas. These keys provide full access to your account."
        type="info"
        showIcon
        className="api-keys-alert"
        style={{ marginBottom: 20 }}
      />
      
      <Alert
        message="API keys will be automatically disabled when team account balance is insufficient"
        description="If your team API key shows as disabled, please contact your team administrator to recharge before using it."
        type="warning"
        showIcon
        className="api-keys-alert"
        style={{ marginBottom: 20 }}
      />

      <Table
        columns={columns}
        dataSource={apiKeys}
        rowKey="id"
        style={{ marginTop: 16 }}
      />

      {/* Create API Key Modal */}
      <Modal
        title="Generate API Key"
        open={isModalVisible}
        onOk={handleCreate}
        onCancel={handleCancel}
        confirmLoading={confirmLoading}
      >
        <Form
          form={form}
          layout="vertical"
        >
          <Form.Item
            name="name"
            label="API Key Name"
            rules={[{ required: true, message: 'Please enter a name for this API key' }]}
          >
            <Input placeholder="Enter a name to identify this API key" />
          </Form.Item>

          <Form.Item
            name="ownerType"
            label="Key Owner"
            rules={[{ required: true, message: 'Please select the owner type' }]}
          >
            <CustomSelect
              placeholder="Select key owner type"
              onChange={(value) => {
                if (value === 'personal') {
                  form.setFieldsValue({ ownerId: 'personal' });
                } else {
                  form.setFieldsValue({ ownerId: undefined });
                }
              }}
            >
              <Option value="personal" disabled={existingOwners.personal}>
                Personal {existingOwners.personal && '(Already exists)'}
              </Option>
              <Option value="team">Team</Option>
            </CustomSelect>
          </Form.Item>

          <Form.Item
            noStyle
            shouldUpdate={(prevValues, currentValues) => prevValues.ownerType !== currentValues.ownerType}
          >
            {({ getFieldValue }) => {
              const ownerType = getFieldValue('ownerType');
              return ownerType === 'team' ? (
                <Form.Item
                  name="ownerId"
                  label="Team"
                  rules={[{ required: true, message: 'Please select a team' }]}
                >
                  <CustomSelect placeholder="Select a team">
                    {teams.map(team => (
                      <Option 
                        key={team.id} 
                        value={team.id} 
                        disabled={existingOwners.teamIds.includes(team.id)}
                      >
                        {team.name} {existingOwners.teamIds.includes(team.id) && '(Already has a key)'}
                      </Option>
                    ))}
                  </CustomSelect>
                </Form.Item>
              ) : null;
            }}
          </Form.Item>
        </Form>
      </Modal>

      {/* Display New API Key Modal */}
      <Modal
        title="Your New API Key"
        open={newKeyVisible}
        onCancel={() => setNewKeyVisible(false)}
        footer={[
          <Button key="copy" type="primary" icon={<CopyOutlined />} onClick={() => handleCopyKey(newKeyValue)}>
            Copy to Clipboard
          </Button>,
          <Button key="close" onClick={() => setNewKeyVisible(false)}>
            Close
          </Button>
        ]}
        className="api-key-display-modal"
        width={580}
        centered
      >
        <Alert
          message="API Key Generated Successfully"
          description="Your API key has been generated and is now available for use. You can always view it again in the API Keys list."
          type="success"
          showIcon
          className="api-keys-alert"
          style={{ marginBottom: 24 }}
        />
        <Paragraph>
          <Text strong style={{ fontSize: '15px', color: '#ffffff', display: 'block', marginBottom: '12px' }}>Your API Key:</Text>
        </Paragraph>
        <div style={{ position: 'relative' }}>
          <Text 
            code 
            copyable={false} 
            style={{ 
              wordBreak: 'break-all', 
              display: 'block', 
              padding: '20px', 
              backgroundColor: '#0c1524', 
              border: '1px solid #234372', 
              borderRadius: '6px', 
              fontSize: '14px',
              color: '#1890ff',
              fontFamily: 'SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace'
            }}
          >
            {newKeyValue}
          </Text>
          <div 
            style={{ 
              position: 'absolute', 
              top: '12px', 
              right: '12px',
              background: 'rgba(12, 21, 36, 0.6)',
              borderRadius: '4px',
              padding: '4px'
            }}
          >
            <Button 
              type="text" 
              icon={<CopyOutlined />} 
              onClick={() => handleCopyKey(newKeyValue)}
              style={{ color: '#1890ff' }}
            />
          </div>
        </div>
        <Paragraph style={{ marginTop: '16px', color: 'rgba(255, 255, 255, 0.65)' }}>
          Use this key to authenticate your API requests. For security, do not share this key publicly.
        </Paragraph>
      </Modal>
    </Card>
  );
};

export default ApiKeys;